# kubernetes version
kubernetes_version: v1.6.5
# you can define your own token or let the system
# automatically generate one for you. 
kubeadm_token: 62af06.d28bf88c95be9639

#contiv version
contiv_version: 1.1.0
ntp_server: ntp.esl.cisco.com

#contiv etcd information
contiv_etcd_version: 3.0.17
contiv_etcd_advertise_port: 6667
contiv_etcd_listen_port: 6666

# proxy info
http_proxy: http://proxy-wsa.esl.cisco.com:80
https_proxy: http://proxy-wsa.esl.cisco.com:80
no_proxy: localhost,127.0.0.1,172.28.225.135

# yum repository
local_repo: http://172.28.225.135/kubam/centos7.3/
